In [ ]:
# SQL - PYTHON Connect

In [1]:
#pip install sqlalchemy
#pip install pymysql

In [3]:
# libraries (install if required)
from sqlalchemy import create_engine, text
import pymysql
import pandas as pd
import os

In [4]:
# URL-encode special chars in password if any (e.g., # -> %23, @ -> %40)  #Pass@123 - Pass%40123
engine1 = create_engine("mysql+pymysql://root:Mysql%40123@localhost:3306/piit")
# URL-encode special chars in password if any (e.g., # -> %23, @ -> %40)  #Pass@123 - Pass%40123
#engine1 = create_engine("mysql+pymysql://root:piit2026@localhost:3306/piit")
print(engine1)
#setting up connection mysql with user name - piuser, pwd - Pass@123 and to database piit at port no  3306

Engine(mysql+pymysql://root:***@localhost:3306/piit)

In [5]:
# function to run the query with parameters or query
def q(sql, **params):
    with engine1.connect() as conn:
        return pd.read_sql(text(sql), conn, params=params)

In [6]:
q("SELECT * FROM students")

,id,name,branch,score,exam_date,remarks
0,1,Rick Johnson,Mechanical,63.68,2025-03-30,Average
1,2,Shannon Hall,Electrical,74.35,2024-03-28,Outstanding
2,3,Stephanie Flores,Computer Science,88.97,2024-05-17,Average
3,4,Keith Ferrell,Civil,75.00,2025-06-22,Average
4,5,Corey Allen,Computer Science,63.14,2025-05-17,Needs Improvement
...,...,...,...,...,...,...
149,26,Alexandra Alexander,Electronics,55.09,2025-04-13,Outstanding
150,27,Anna Zimmerman,Civil,83.72,2024-10-28,Average
151,28,Michael Johnson,Electronics,78.04,2024-07-05,Average
152,29,Michael Higgins DDS,Computer Science,90.45,2025-02-20,Outstanding
153,30,Jodi Chapman,Electronics,54.13,2025-07-04,Needs Improvement

In [7]:
q("select * from students where id > 5")

,id,name,branch,score,exam_date,remarks
0,6,Brittney Galloway,Computer Science,51.85,2025-02-01,Needs Improvement
1,7,Kathryn Gordon,Electrical,70.88,2023-12-10,Outstanding
2,8,Julia Warren,Electrical,63.07,2023-11-21,Needs Improvement
3,9,Carol Cunningham,Computer Science,87.88,2024-07-29,Good
4,10,Cassidy Crawford,Civil,52.46,2025-02-25,Excellent
...,...,...,...,...,...,...
124,26,Alexandra Alexander,Electronics,55.09,2025-04-13,Outstanding
125,27,Anna Zimmerman,Civil,83.72,2024-10-28,Average
126,28,Michael Johnson,Electronics,78.04,2024-07-05,Average
127,29,Michael Higgins DDS,Computer Science,90.45,2025-02-20,Outstanding
128,30,Jodi Chapman,Electronics,54.13,2025-07-04,Needs Improvement